# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

parameters:
  - name: WORKING_DIRECTORY
    type: string

steps:
  - task: DownloadSecureFile@1
    name: vmKey
    displayName: 'Download VM Key'
    inputs:
      secureFile: 'azureVMSSHKey'

  - script: |
      echo "Copying the VM Key to ~/.ssh and setting permissions"
      mkdir ~/.ssh
      sudo mv $(vmKey.secureFilePath) ~/.ssh/azure_id_rsa
      sudo chmod 400 ~/.ssh/azure_id_rsa
    displayName: 'Setup VM SSH Key'

  - template: ./utils/get-bastion-node-ip.yaml

  - task: AzureCLI@2
    displayName: Initiate performance test run
    inputs:
      azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
      scriptType: bash
      useGlobalConfig: true
      scriptLocation: scriptPath
      scriptPath: '${{ parameters.WORKING_DIRECTORY }}/init_perf_run.sh'
      addSpnToEnvironment: true
    env:
      BUILD_NUM: $(Build.BuildNumber)
      BUILD_PURPOSE: "Populate Test Data"
      GITHUB_USER_EMAIL: $(gitEmail)
      GITHUB_USERNAME: $(gitUsername)
      BUILD_TYPE: $(Build.Reason)
      BUILD_PATH: $(Build.ArtifactStagingDirectory)
      DATABASE_HOST_NAME: 'postgresql-thunder-perf-eastus2-001.postgres.database.azure.com'
      THUNDER_HOST_NAME: 'thunder.local'
      POPULATE_TEST_DATA: "true"
      RUN_MODE: "NONE"
      CONCURRENCY: 10
      BASTION_NODE_IP: $(BASTION_NODE_IP)
      WORKSPACE: ${{ parameters.WORKING_DIRECTORY }}
